# syntax=docker/dockerfile:1

FROM golang:1.19-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
COPY . .

RUN go mod download
RUN go build ./chapter05/cmd
RUN apk --no-cache add curl
EXPOSE 3000

CMD [ "./cmd" ]