// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Number is an autogenerated mock type for the Number type
type Number struct {
	mock.Mock
}

type mockConstructorTestingTNewNumber interface {
	mock.TestingT
	Cleanup(func())
}

// NewNumber creates a new instance of Number. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNumber(t mockConstructorTestingTNewNumber) *Number {
	mock := &Number{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
